# 告警规则配置文件示例
# cat prometheus/rules/docker_monitor.yml 
groups:
- name: "container monitor"
 rules:
- alert: "Container down: env1"
expr: time() - container_last_seen{name="env1"} > 60
for: 30s
labels:
 severity: critical
annotations:
 summary: "Container down: {{$labels.instance}} name={{$labels.name}}"